### ISSUE TITLE
Criação da Home Page

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#10]
Descrição: Esta tarefa foca na construção e implementação do conteúdo da página inicial do site, utilizando o design já estabelecido como referência. O objetivo é traduzir de forma fiel e eficaz os elementos visuais e funcionais do design em conteúdo real, assegurando que a mensagem e a identidade da marca sejam comunicadas de maneira clara e atrativa aos visitantes.

caso fique alguma duvida nessa tarefa me contatar @ProBeta12

**Comment by JosielSantos16** [comment]
Segue-se a HomePage desenvolvida e atualizada : 

![Image](https://github.com/user-attachments/assets/293b4a76-f04d-49eb-a50e-afcd7718eab0)

![Image](https://github.com/user-attachments/assets/1e329c55-7709-4d26-8874-904caa6e8be5)

![Image](https://github.com/user-attachments/assets/558bbad6-0c40-49b4-8302-d013603bb139)

![Image](https://github.com/user-attachments/assets/105fd4ef-f47b-49e0-aa86-b525cf759e7b)

![Image](https://github.com/user-attachments/assets/df813467-3cf1-45f9-819a-bdb87ab6e3db)
