### ISSUE TITLE
Criação de Wireframe Website de Alta Fidelidade

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#11]
Descrição: Esta tarefa consiste em criar wireframes de alta fidelidade para a versão mobile do website. Wireframes de alta fidelidade incluem detalhes visuais mais elaborados, tipografia, e espaçamentos precisos, representando uma versão mais próxima do design final.

Tópicos iniciais para a criação das telas:

- [x] Sites referenciais
- [x] Paleta de Cores
- [x] definição de funcionalidades/animações

**Comment by LayaneBentes** [comment]
Fiz umas pesquisa das paletas de cores que podem ser utilizadas no site.

Site utilizado na pesquisa: https://color.adobe.com/pt/explore

<img src="https://github.com/user-attachments/assets/7d874f7c-f5ff-4b40-9bff-bb7b6bf2c181" alt="Image" width="300" height="200">

<img src="https://github.com/user-attachments/assets/863a4f2d-02f2-41ef-a9cb-b4c7bf1428d4" alt="Image" width="300" height="200">

<img src="https://github.com/user-attachments/assets/9e448dd6-32e0-405b-b2fd-b5d79bef3725" alt="Image" width="300" height="200">

**Comment by ProBeta12** [comment]
Criei um projeto no figma para nós criar as telas de alto nivcel.
link  figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&m=dev&t=LC2Vh2EraY9en3zL-1

**Comment by ProBeta12** [comment]
Temos o designer de baixo nivel  na seguinte tarefa: #8

**Comment by ProBeta12** [comment]
@LayaneBentes  estou fazendo as telas sem a paleta de cores para terminar logo as funções básicas do site, assim a equipe dev ja consegue começar a fazer a tela home.

**Comment by LayaneBentes** [comment]
@ProBeta12, decidi escolher a "paleta de cores 1" (#11), para aplicar no site.

**Comment by ProBeta12** [comment]
Terminei o wireflame de alta fidelidade, segue o link do figma e suas telas em pdf:
figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&t=sWusTV0XqckZvqMU-1
documento: 

[heavenly.pdf](https://github.com/user-attachments/files/16382660/heavenly.pdf)
