### ISSUE TITLE
Definição do Wireflow das telas

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#12]
Descrição: Esta tarefa envolve a definição do wireflow das telas, focando inicialmente na versão mobile. Wireflows combinam wireframes e fluxogramas para mostrar a interação e a navegação do usuário entre diferentes telas.

Objetivos: 

- [x]  Mapear a navegação e as interações do usuário nas telas mobile. 

- [x]  Documentar as transições e fluxos entre diferentes páginas.

- [x]  Garantir uma experiência de usuário intuitiva e coesa.

- [x]  Servir como referência para o desenvolvimento da versão web, mantendo a consistência na navegação e interação.

**Comment by LayaneBentes** [comment]
Iniciei a wareflow da tela para questão de melhor visualização dos fluxos entre telas, as telas estão sujeitas a modificações.



![Image](https://github.com/user-attachments/assets/4afa4b9d-0b9b-4b7d-9483-1e0824bccfd0)

**Comment by ProBeta12** [comment]
Dei uma revisada. o fluxo esta bom pra seguir como inicio.

**Comment by LayaneBentes** [comment]
Organizei melhor o fluxo de telas.

Link onde o fluxo está para melhor visualização: https://miro.com/app/board/uXjVN1XWAAk=/?utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=view-board-cta
