### ISSUE TITLE
Implementação dos Componentes Básicos

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#14]
Descrição: Esta tarefa envolve a criação e implementação dos componentes básicos e essenciais do site, incluindo o menu, a navegação e o footer. 

Objetivos:

- [x] Menu de Navegação: Criar um componente de menu que permita aos usuários acessar facilmente as diferentes seções do site.

- [x] Navegação: Implementar a lógica de navegação para assegurar que as transições entre páginas sejam suaves e intuitivas.

- [x] Footer: Desenvolver um componente de footer que contenha informações essenciais e links úteis.

**Comment by ProBeta12** [comment]
@markosokada 
Siga o designer do figma na tarefa: #11  
link figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&t=2TXqG2FkiOYmrhxc-1

**Comment by markosokada** [comment]
Menu de navegação concluído.

**Comment by markosokada** [comment]
iniciei hoje a pesquisar sobre implementação da logica de navegação, me pareceu uma documentação que precisar se  apresentada , porém ainda não concli miha pesquisa porisso naõ iniciei a implementaçã.
em vez disso foquei no desenvolvimento do footer; me pareceu mais lógico pois o prazo está bem apertado e pretendo enteregar essa tag o mais rápdo póssivel parta dar inicio a integração da API'S.

**Comment by markosokada** [comment]
footer quase finalizado, tenhoo que ajustar algumas estilizações, mas acredito que entrego amanha.

**Comment by LayaneBentes** [comment]
Terminei o menu NavBar, mas não consegui rodar no meu notebook, por favor, verifiquem se estar funcionando.

**Comment by ProBeta12** [comment]
@LayaneBentes  estava  com alguns erros de css causado pelo tailwind e de estilo, fiz a correção.

**Comment by ProBeta12** [comment]
ja revisei, podemos continuar com as outras telas.
