### ISSUE TITLE
Definir estrutura de pastas

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#15]
Descrição: Esta tarefa envolve a definição da estrutura de pastas para o projeto, baseada no padrão de arquitetura MVC (Model-View-Controller).

Objetivos:

- [x] Organizar o código do projeto de maneira lógica e coerente.

- [x] Separar as responsabilidades de cada componente (Model, View e Controller).

- [x] Facilitar a manutenção e escalabilidade do projeto.
- [x] documentar funcionalidade de cada pasta.

**Comment by ProBeta12** [comment]
vou criar uma feacture para essa tarefa .... feacture/Definir-estrutura-de-pastas

**Comment by LayaneBentes** [comment]
Revisei a documentação, bem explicativo, consegui compreender a utilidade de cada pasta.
