### ISSUE TITLE
Criação de Documentação

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#18]
Descrição: Esta tarefa envolve a elaboração e organização da documentação detalhada referente à sprint atual. O objetivo é registrar de maneira clara e concisa todas as atividades, decisões, e resultados da sprint, assegurando que a equipe e as partes interessadas tenham acesso a informações precisas e completas sobre o progresso e os resultados alcançados.

**Comment by ProBeta12** [comment]
Relatório da Sprint 1

documento: 

[Relatório da Sprint 1_ Heavenly - Celestial.pdf](https://github.com/user-attachments/files/16333008/Relatorio.da.Sprint.1_.Heavenly.-.Celestial.pdf)

**Comment by LayaneBentes** [comment]
Revisei a documentação, 

Tudo está de acordo com o que ocorreu na primeira sprint, este relatório serve como referência para que  principalmente possamos vê o que conseguimos realizar e como o atraso pode influenciar no processo da realização de novas issues, que sirva de exemplo para que possamos também enxergar nosso desenvolvimento como equipe: o que precisamos melhorar, o que podemos modificar, para que sejamos capazes de criar rotinas que venham gerar uma maior produtividade para cada um de nós.
