### ISSUE TITLE
Criação de telas pendentes

### ISSUE THREAD

**Issue by JosielSantos16** [victo-dev-qriarlabs/heavenly#22]
Descrição: Desenvolver todas as telas que ainda estão pendentes no projeto, garantindo a implementação completa do design de baixa fidelidade das seguintes telas:

- [x] #27 

- [x] #28 

- [x] #29

**Comment by ProBeta12** [comment]
Estou pegando essa tarefa para ver como esta a organização das telas e sua produção.

**Comment by ProBeta12** [comment]
@JosielSantos16 continue concertando o estilo do site, tem que ficar o mais fiel possível com o designer do figma.
faça uma nova feature para isso e coloque o link para ela no comentário da tarefa. Os commits devem ser feitos com o tipo style.
ex: "style: correção das fontes  usadas".

**Comment by JosielSantos16** [comment]
Criei uma feature chamada "correcao_estilo" para corrijir os estilos das telas

**Comment by LayaneBentes** [comment]
Criei uma feature para tratar dos textos que irão ter nas telas de: constelações e duvidas comuns.

segue o nome da feature: feature/utilizaveis-aba-constelacao-duvidas

**Comment by LayaneBentes** [comment]
@ProBeta12 , baixei outra imagem para o fundo do site: 360 x 1080 px (SVG), oberve se o GitHub suporta.

**Comment by markosokada** [comment]
revisando conceitos de tailwind e testando reponsividade de telas.

**Comment by ProBeta12** [comment]
@LayaneBentes @LayaneBentes @markosokada  vou finalizar essa tarefa na sprint 2 e organizar o backlog

**Comment by ProBeta12** [comment]
Para fins de organização, estamos encerrando a tarefa atual e abrindo novas tarefas subsequentes relacionadas à estilização das telas. As telas estão funcionalmente completas, mas estamos enfrentando alguns erros de estilização em várias delas. A nova tarefa se concentrará na correção desses problemas de estilização para garantir uma apresentação visual.
