### ISSUE TITLE
Correção de Estilização na Página de Horóscopo

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#27]
Descrição: Esta tarefa foca na construção e implementação do conteúdo da tela do horoscopo do site, utilizando o design já estabelecido como referência.  

figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&t=sWusTV0XqckZvqMU-1
documento: [heavenly.pdf](https://github.com/user-attachments/files/16382660/heavenly.pdf)

**Comment by ProBeta12** [comment]
@JosielSantos16 Além de criar uma nova página para redirecionamento individual de cada horóscopo de signo a partir da página principal de horóscopo, é necessário corrigir os espaçamentos entre os componentes e ajustar as fontes.

**Comment by JosielSantos16** [comment]
Fiz a implementação dessa tela e das outra e subi os commits, estou esperando a revisao

**Comment by ProBeta12** [comment]
@JosielSantos16 a revisão dessa tarefa esta na tarefa de integração #32
