### ISSUE TITLE
Correção de Estilização na Página Dúvidas comuns

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#28]
Descrição: Esta tarefa foca na construção e implementação do conteúdo da tela do horoscopo do site, utilizando o design já estabelecido como referência.  

figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&t=sWusTV0XqckZvqMU-1
documento: [heavenly.pdf](https://github.com/user-attachments/files/16382660/heavenly.pdf)

**Comment by ProBeta12** [comment]
@JosielSantos16 Adicionar uma imagem de apresentação à página de Dúvidas Comuns para melhorar o layout visual. Além disso, ajustar os cards de dúvidas para aumentar o espaçamento em relação às bordas da tela e garantir um alinhamento adequado.

**Comment by ProBeta12** [comment]
@JosielSantos16  revisei a tela e o componente de duvidas comuns esta quebrando o css, pode dar uma olha, esta afetando o fundo do site e o componente de "veja as constelações de se cada signo.
