### ISSUE TITLE
Correção de Estilização na Página constelação

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#29]
Descrição: Esta tarefa foca na construção e implementação do conteúdo da tela do horoscopo do site, utilizando o design já estabelecido como referência.  

figma: https://www.figma.com/design/LHfEJj3BFN0PdH3D8do8fW/heavenly?node-id=0-1&t=sWusTV0XqckZvqMU-1
documento: [heavenly.pdf](https://github.com/user-attachments/files/16382660/heavenly.pdf)

**Comment by ProBeta12** [comment]
@JosielSantos16 Além de criar uma nova página para redirecionamento individual de cada constelação de signo a partir da página principal de Constelação, é necessário corrigir os espaçamentos entre os componentes e ajustar as fontes.

**Comment by JosielSantos16** [comment]
Fiz a correção dos espacamentos do css e das fontes e outras pequenas auterações

**Comment by ProBeta12** [comment]
Revisei os  o código puxando para meu ambiente dev, esta muito bom as correções. Um ponto de atenção seria colocar mais detalhes de onde foi corrigido na tarefa, tipo imagens mostrando a correção e o erro de estilização.
