### ISSUE TITLE
Integração de APIs

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#3]
Descrição: Esta tarefa envolve a configuração e desenvolvimento da integração de APIs necessárias para o projeto. O objetivo é garantir que as diferentes partes do sistema possam se comunicar de forma eficiente e segura através de interfaces de programação de aplicativos (APIs), tanto internas quanto externas.

Objetivos:

- [x] Configuração de Endpoints: Definir endpoints e métodos HTTP (GET, POST, PUT, DELETE) para cada API.

- [x] Testes de Integração: Realizar testes para verificar a correta integração das APIs, garantindo que elas respondam conforme esperado e manipulem dados de forma segura.

Documentação: Criar documentação clara e detalhada para cada API, descrevendo endpoints, parâmetros, formatos de resposta e exemplos de uso. Essa documentação faz referencia aos endpoints usados no projeto. 

Tarefas referentes

- [x] #5

**Comment by ProBeta12** [comment]
Criação de uma feature para a integração com a API de horóscopo. Esta feature inclui a implementação da lógica para fazer chamadas à API, tratamento de respostas e exibição dos dados de horóscopo no componente correspondente.
segue a feature: feature/integracao-api

**Comment by ProBeta12** [comment]
criei um arquivo chamado rapidapi.js na pasta services, para ser usado como comunicação com a api, o arquivo faz uma solicitação do tipo GET referente ao seu signo, ela retorna o horoscopo diario do signo correspondente. Ele pode ser chamado no componente horoscopo do dia.


![Image](https://github.com/user-attachments/assets/3952efd8-9968-47fe-93be-9ea6496adb39)
