### ISSUE TITLE
Adaptação de Telas Mobile para Desktop

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#31]
Descrição: Ajustar e otimizar o layout das páginas, originalmente desenvolvidas para dispositivos móveis, para garantir uma experiência de usuário consistente e funcional em telas de desktop. A tarefa inclui:

- Adaptação e ajustes de CSS para telas maiores.

- Testes em diversos navegadores e resoluções de tela de desktop.

- Correção de quaisquer problemas de layout que possam surgir durante o teste.

**Comment by markosokada** [comment]
iniciei a adaptação pelo componente horóscopo do dia.

**Comment by JosielSantos16** [comment]
Fiz a responsividade do banner e umas pequenas alterações na navbar. 

No momento esta assim :

![Image](https://github.com/user-attachments/assets/aa5d08db-6295-4749-a3fa-2695ffcf6870)

**Comment by ProBeta12** [comment]
falta terminar o footer , no tamanho xl ela nao esta responsiva.


![Image](https://github.com/user-attachments/assets/2ad10cfd-58b1-4291-af9c-aa05df2e68f8)

**Comment by markosokada** [comment]
Finalizado a responsividade das página home, dúvidas comuns do horóscopo do dia.

**Comment by ProBeta12** [comment]
Adicionei as descrições d o readme do projeto em geral e da execução do projeto.

**Comment by ProBeta12** [comment]
finalizei o footer e corrigi alguns erros de espaçamento.
![Captura de tela 2024-08-03 134416](https://github.com/user-attachments/assets/7482dc17-54c2-483c-a523-c534e3caceda)

**Comment by ProBeta12** [comment]
tarefa revisada.
tarefa feita na branch: Feature/telas responsiveis 
#41
