### ISSUE TITLE
Criação de Fundo Animado com Estrelas

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#34]
Descrição:

- [x] Desenvolver e implementar um fundo animado para o site que consiste em um fundo preto com estrelas se movendo. A tarefa inclui:

Desenvolvimento da Animação:

- [x] Criar uma animação de estrelas em movimento para o fundo do site, utilizando técnicas como CSS animations, tailwind ou JavaScript/react com bibliotecas adequadas.

Implementação do Fundo:

- [x] Aplicar o fundo preto e a animação de estrelas no site, garantindo que a animação seja fluida e não afete o desempenho geral da página.

 Otimização e Testes:

- [x] Testar o fundo animado em diferentes navegadores e dispositivos para assegurar compatibilidade e desempenho.

Ajustar a animação conforme necessário para garantir que ela se integre bem com o restante do design do site.

**Comment by LayaneBentes** [comment]
Criei a animação de estrelas utilizando técnicas do CSS animations com a cor de fundo preta como descrita na issue.
A animação ainda não foi aplicada ao fundo do site, criei em um arquivo separado.

![Image](https://github.com/user-attachments/assets/0fbf70e0-1b7e-4b3a-8ef1-b805dda43c49)

**Comment by LayaneBentes** [comment]
Testei a animação em diferentes navegadores:

1. Microsoft Edge
2. Mozilla Firefox
3. Google Chrome
4. Opera
5. Brave


![Image](https://github.com/user-attachments/assets/b367340d-74a8-4021-ac2e-2b20cb5992a7)


**TESTES APROVADOS:**

**2. Mozilla Firefox**
![Image](https://github.com/user-attachments/assets/ea30ec7f-2cae-489d-b7f0-51e58b081b05)
**3. Google Chrome**
![Image](https://github.com/user-attachments/assets/3cf3b579-95a7-45f1-8207-5be976968dd1)
**4. Opera**
![Image](https://github.com/user-attachments/assets/bbbdbeda-df40-4622-a25d-89d5bc254788)
**5. Brave**
![Image](https://github.com/user-attachments/assets/390bb48e-0a5a-48d2-89d4-e8d27efc74d7)

**TESTES NÃO APROVADOS:**

**1. Microsoft Edge**
![Image](https://github.com/user-attachments/assets/408e88ea-90fb-4ea1-a776-63ea577b1573)
