### ISSUE TITLE
Configuração de ferramentas dev

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#4]
Descrição: Esta tarefa envolve a instalação e configuração das ferramentas de desenvolvimento necessárias para garantir um ambiente de trabalho eficiente e produtivo para todos os desenvolvedores da equipe. 

Objetivo:

- [x] Criar um documento contendo todas as Stacks usadas no projeto e suas versões.

Ferramentas:

- [x] git
- [x] React
- [x] Node
- [x] JavaScript
- [x] Tailwind CSS
- [x] BootStrap
- [x] HTML
- [x] CSS

**Comment by JosielSantos16** [comment]
Seguir a documentação relativa as stacks usadas no projetos:



[Documento de Stacks e Ferramentas de Desenvolvimento.pdf](https://github.com/user-attachments/files/16289475/Documento.de.Stacks.e.Ferramentas.de.Desenvolvimento.pdf)

**Comment by ProBeta12** [comment]
Eu adicionei o  git na descrição da tarefa para ser adicionado no documento, e também verifiquei o link do node e não esta pegando @JosielSantos16  pode dar uma olhada.

**Comment by ProBeta12** [comment]
ja atualizei o documento:
[Documento.de.Stacks.e.Ferramentas.de.Desenvolvimento pronto.pdf](https://github.com/user-attachments/files/16314805/Documento.de.Stacks.e.Ferramentas.de.Desenvolvimento.pronto.pdf)

**Comment by LayaneBentes** [comment]
Revisei a documentação, está boa, da de compreender !
