### ISSUE TITLE
Definir APIs de uso

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#5]
Descrição: Esta tarefa envolve a identificação e definição das APIs que serão utilizadas no projeto. Isso inclui tanto APIs internas, desenvolvidas pela própria equipe, quanto APIs externas, fornecidas por terceiros. O objetivo é garantir que todas as integrações necessárias estejam claramente especificadas, documentadas e acessíveis para os desenvolvedores.

Objetivos:

- [x] Identificação de APIs Necessárias: Determinar todas as APIs que o projeto precisará utilizar, seja para integração com serviços externos ou funcionalidades internas.

- [x] Documentação de APIs: Deixar uma explicação simples como funciona a API e deixar o link da sua documentação. Posteriormente será usada para conexão.

**Comment by markosokada** [comment]
Horoscope API -> API  que retorna o horoscopo do dia.(Free,pt-br)
Comando do shell:
curl --request GET \
	--url https://horoscope-api.p.rapidapi.com/pt/aquario \
	--header 'x-rapidapi-host: horoscope-api.p.rapidapi.com' \
	--header 'x-rapidapi-key: efea90830fmsh3f86299655aff51p1c237djsn1bdcb6aebe04'

Horoscope Astrology -> API  que retorna o horoscopo do dia, ontem , amanha, da semana, mês e ano.(Freemium-en)
retorna também as compatibiliadades entre os signos( relacionamento amorosos)
Comando do shell:
curl --request GET \
	--url 'https://horoscope-astrology.p.rapidapi.com/affinity?sign1=libra&sign2=aries' \
	--header 'x-rapidapi-host: horoscope-astrology.p.rapidapi.com' \
	--header 'x-rapidapi-key: efea90830fmsh3f86299655aff51p1c237djsn1bdcb6aebe04'

Horoscope ->API que retorna os horoscopos em datas especificas, não precisa escolher o signo apenas a a data retorna o horoscopo da data escolhida de todos os signos(Freemium-en)
Commando do shell:
curl --request GET \
	--url 'https://horoscope34.p.rapidapi.com/api/horoscope/byDate?date=2023-05-02' \
	--header 'x-rapidapi-host: horoscope34.p.rapidapi.com' \
	--header 'x-rapidapi-key: efea90830fmsh3f86299655aff51p1c237djsn1bdcb6aebe04'

**Comment by ProBeta12** [comment]
Ta muito bom, finalizando tarefa.
