### ISSUE TITLE
Definir branchs padrão

### ISSUE THREAD

**Issue by ProBeta12** [victo-dev-qriarlabs/heavenly#7]
Descrição: Esta tarefa envolve a configuração e definição de branches padrão no repositório Git, seguindo o fluxo de trabalho baseado em branches main, develop e feature. Esse fluxo ajuda a organizar o desenvolvimento, permitindo uma gestão eficiente das funcionalidades em desenvolvimento, integração contínua e lançamentos estáveis.

Passos para Implementação

1. Criar e Configurar Branches: 

- [x] Estabelecer a branch main como a branch de produção.

- [x] Criar a branch develop a partir da branch main e configurá-la como a branch de desenvolvimento.

- [x] Definir a convenção de nomenclatura para branches de feature (ex.: feature/nome-da-feature).

2. Fluxo de Trabalho:
    
    Branch main:
     - Somente código estável e pronto para produção deve ser mesclado nesta branch.
     - Releases são criados a partir desta branch.
    
    Branch develop: 
     - Integração contínua de código desenvolvido em branches de feature. 
     - Antes de cada release, a branch develop é mesclada na branch main.
    
    Branches feature: 
     - Criadas a partir da branch develop para cada nova funcionalidade ou melhoria. 
     - Após a conclusão e revisão do código, as branches de feature são mescladas de volta na branch develop.
    
    Integração e Revisão:
     - Implementar políticas de pull request (PR) para garantir que o código nas branches de feature seja revisado antes de ser mesclado na branch develop.
    
    Documentação e Comunicação:
     - Documentar o fluxo de trabalho e convenções de branches em um guia de contribuição para a equipe de desenvolvimento.
     - Comunicar claramente a estrutura e práticas de branches para todos os membros da equipe.

**Comment by ProBeta12** [comment]
Seguir a documentação o fluxo de trabalho e convenções de branches em um guia de contribuição para a equipe de desenvolvimento:

**Comment by ProBeta12** [comment]
doc

**Comment by LayaneBentes** [comment]
Já revisei a documentação, esta ótima.
