### ISSUE TITLE
Criação de Wireframe Website  de Baixa Fidelidade 

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#8]
Descrição: Desenvolver um wireframe de baixa fidelidade para o website. Este wireframe deve capturar a estrutura básica e o layout das principais páginas e componentes, sem se preocupar com detalhes de design ou estilização. O objetivo é ter uma visão geral da disposição dos elementos e da navegação entre as telas.

Sites referenciais
Esses são os sites que temos como referencia atualmente.

1. https://www.astrolink.com.br/
2. https://www.personare.com.br/horoscopo?tm=tt&ap=gads&aaid=ada9OVCiM4aHO&utm_source=google&utm_medium=cpc&utm_campaign=pareto.ac.gsn.brand.br.Institucional&utm_term=pareto.AG.MarcaHP&gad_source=1&gclid=CjwKCAjwy8i0BhAkEiwAdFaeGIlDN-F9K6j5imvoiosUq8DnFtGE3dgccaY-wjL8B1n5EcCrpBoWiRoCv-0QAvD_BwE

**Comment by LayaneBentes** [comment]
Fiz o protótipo da wareframe de baixa fidelidade inicial, precisa-se de uma analise dos outros integrantes da equipe.

O protótipo se encontra no Miro: https://miro.com/app/board/uXjVN1XWAAk=/



![Image](https://github.com/user-attachments/assets/02482364-87c3-42ea-afcd-d4df1a185478)

**Comment by LayaneBentes** [comment]
Modifiquei 3 campos da wareframe:

Alterações:

1. Diminui o quadro do campo: constelações.
3. Removi os quadrados de dúvidas comuns e fiz um único componente de chamada para outra página.
4. Removi o campo de busca da parte final da tela home.



![Image](https://github.com/user-attachments/assets/3d56142e-2cb2-4fb9-8283-7f2de7c91781)

**Comment by ProBeta12** [comment]
Telas finalizadas.

Tela Home: Contém os principais elementos do wireframe.

![Image](https://github.com/user-attachments/assets/5bffa58c-9b97-4fd0-acbc-d76be4b378d5)

Tela Horóscopo: Exibe informações conforme o signo selecionado na Tela Home.

![Image](https://github.com/user-attachments/assets/e02b4a55-8d02-4944-ac80-24c63012fc91)

Tela de Dúvidas Comuns: Apresenta informações baseadas na dúvidas escolhida na Tela Home.

![Image](https://github.com/user-attachments/assets/4f2c2d8a-c948-496b-ae6a-c03e2a8b7ceb)

Tela de Constelações: Fornece detalhes sobre a constelação referente ao signo selecionado na Tela Home.

![Image](https://github.com/user-attachments/assets/66ccb06f-b6ab-46cc-be1e-b029c3ac2501)
